version: "3.1"
services:
  yoshiyaki:
    container_name: yoshiyaki
    # depends_on:
    #   - sqlite
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:80
    networks:
      - app-network
    volumes:
      - ./src:/var/www/html

  # sqlite:
  #   container_name: sqlite
  #   image: nouchka/sqlite3:latest
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./src/config/db:/root/db

  # adminer:
  #   container_name: adminer
  #   build:
  #     context: adminer
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - sqlite
  #   ports:
  #     - 5001:8080
  #   networks:
  #     - app-network
  #   environment:
  #     - ADMINER_PLUGINS=login-password-less
  #   privileged: true
  #   volumes:
  #     - ./src/config/db:/db

networks:
  app-network:
    driver: bridge
