# Version
version: "3.1"

# Setup
services:
  # PHP
  dorayaki-dev:
    container_name: dorayaki-dev
    depends_on:
      - sqlite
    build:
      context: ../../
      dockerfile: builds/server/Dockerfile
    restart: always
    ports:
      - 5000:80
    networks:
      - dbconnect
    volumes:
      - ../../:/var/www/html

  # sqlite
  sqlite:
    container_name: sqlite-dev
    image: nouchka/sqlite3:latest
    env_file: ../../builds/database/.env
    stdin_open: true
    tty: true
    networks:
      - dbconnect
    volumes:
      - ../../db/:/root/db/

  #adminer
  adminer:
    image: adminer
    restart: always
    depends_on:
      - sqlite

# networks
networks:
  dbconnect:
    driver: bridge
